# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ra', models.BigIntegerField(unique=True, verbose_name='RA')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='E-Mail')),
                ('primeiro_nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primeiro Nome')),
                ('ultimo_nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Último Nome')),
                ('perfil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Perfil')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('superuser', models.BooleanField(default=False, verbose_name='Admin')),
                ('equipe', models.BooleanField(default=False, verbose_name='Equipe')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'verbose_name': 'Usuário',
            },
        ),
    ]
