# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('ra', models.IntegerField(unique=True, verbose_name='RA')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=50, verbose_name='E-Mail')),
                ('celular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('perfil', models.CharField(choices=[('P', 'Professor'), ('A', 'Aluno'), ('C', 'Coordenador')], max_length=1, verbose_name='Perfil')),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': False,
            },
        ),
    ]
